#!/bin/bash

set -e

VM_NAME=$1
VM_SECURITY=$2
VM_IMAGE=${3:-Canonical:ubuntu-24_04-lts:server:latest}
VM_USER=${AZURE_VM_USER:-azureuser}

if ! [ -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
fi

if [ -z "$3" ]; then
   echo "Assuming generalized image"
   VM_EXTRA_ARGS="--admin-username $VM_USER --ssh-key-value ~/.ssh/id_rsa.pub"
else
   echo "Assuming specialized image" 
   VM_EXTRA_ARGS="--specialized"
fi

if [ -n "$AZURE_VM_USER_DATA" ]; then
   VM_EXTRA_ARGS="$VM_EXTRA_ARGS --user-data $AZURE_VM_USER_DATA"
fi

if [ "$VM_SECURITY" = "SEV-SNP" ]; then
  # AMD SEV-SNP
  VM_SECURITY="ConfidentialVM"
  VM_SIZE="Standard_DC2ads_v5"
  VM_EXTRA_ARGS="$VM_EXTRA_ARGS --os-disk-security-encryption-type VMGuestStateOnly --enable-vtpm --enable-secure-boot"
elif [ "$VM_SECURITY" = "TDX" ]; then
  # Intel TDX
  VM_SECURITY="ConfidentialVM"
  VM_SIZE="Standard_DC2eds_v5"
  VM_EXTRA_ARGS="$VM_EXTRA_ARGS --os-disk-security-encryption-type VMGuestStateOnly --enable-vtpm --enable-secure-boot"
elif [ "$VM_SECURITY" = "vTPM" ]; then
  # TrustedLaunch
  VM_SECURITY="TrustedLaunch"
  VM_SIZE="Standard_D4ds_v5"
else
  VM_SECURITY="Standard"
  VM_SIZE="Standard_D4ds_v5"
fi

az vm create --resource-group $AZURE_RESOURCE_GROUP \
             --name $VM_NAME \
             --image $VM_IMAGE \
             --size $VM_SIZE \
             --storage-sku StandardSSD_LRS \
             --security-type $VM_SECURITY \
             --nic-delete-option delete \
             --os-disk-delete-option delete \
             --patch-mode ImageDefault \
             --assign-identity [system] \
             $VM_EXTRA_ARGS

az vm boot-diagnostics enable --resource-group $AZURE_RESOURCE_GROUP \
                              --name $VM_NAME
