#!/bin/bash

set -e

VM_NAME=$1
VM_IMAGE=${2:-Canonical:ubuntu-24_04-lts:server:latest}
VM_USER=${AZURE_VM_USER:-azureuser}

if ! [ -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
fi

if [ -z "$2" ]; then
   echo "Assuming generalized image"
   VM_EXTRA_ARGS="--admin-username $VM_USER --ssh-key-value ~/.ssh/id_rsa.pub"
else
   echo "Assuming specialized image" 
   VM_EXTRA_ARGS="--specialized"
fi

az vm create --resource-group $AZURE_RESOURCE_GROUP \
             --name $VM_NAME \
             --image $VM_IMAGE \
             --size Standard_D4ds_v5 \
             --storage-sku StandardSSD_LRS \
             --security-type TrustedLaunch \
             --nic-delete-option delete \
             --os-disk-delete-option delete \
             --patch-mode ImageDefault \
             $VM_EXTRA_ARGS

az vm boot-diagnostics enable --resource-group $AZURE_RESOURCE_GROUP \
                              --name $VM_NAME
