#!/bin/bash

set -e

VM_NAME=$1
VM_USER=${AZURE_VM_USER:-azureuser}

if ! [ -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
fi

az vm create --resource-group $AZURE_RESOURCE_GROUP \
             --name $VM_NAME \
             --image "Canonical:ubuntu-24_04-lts:server:latest" \
             --admin-username $VM_USER \
             --ssh-key-value ~/.ssh/id_rsa.pub \
             --size Standard_D4ds_v5 \
             --security-type TrustedLaunch \
             --nic-delete-option delete \
             --os-disk-delete-option delete \
             --patch-mode ImageDefault

az vm boot-diagnostics enable --resource-group $AZURE_RESOURCE_GROUP \
                              --name $VM_NAME
