# yamllint disable rule:line-length
name: Test for BuildEnv L1 container build

on:
  push:
    branches:
      - main
    paths:
      - 'build-container/**'

permissions:
  id-token: write
  attestations: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build docker container
        id: build
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: "."
          file: "build-container/test-buildenv.dockerfile"
          tags: "test_l1:latest"

      - name: Generate SLSA Provenance
        id: slsa
        uses: actions/attest-build-provenance@520d128f165991a6c774bcb264f323e3d70747f4 # v2.2.0
        with:
          subject-name: "test_l1"
          subject-digest: ${{ steps.build.outputs.digest }}
