name: Test for BuildEnv L1 container build

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: write
jobs:
  build:
    if: github.actor == 'marcelamelara'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4

    - name: Build docker container
      shell: bash
      run: |
        docker build --file build-container/test-buildenv-l1.dockerfile .

    #- name: Generate SLSA Provenance
    #  uses: actions/attest-build-provenance@6149ea5740be74af77f260b9db67e633f6b0a9a1 #v1.4.2
    #  with:
    #    subject-name: 
